config/routes.rb
# -*- encoding : utf-8 -*-
Trans::Application.routes.draw do
  root :to => 'home#index'
  resources :notices do
    collection do
      get :read, :unread
    end
  end
  resources :excels do
    collection do
      get :export_translations
      post :export_translations
    end
  end
  resources :categories
  resources :languages
  resources :documents do
    collection do
      get :uploaded, :batch_new, :batch_assign
      post :batch_create, :batch_assign
    end
    resources :comments
    resources :operations
    resources :translations
  end
  resources :translations do
    collection do
      get :generated, :assigned, :sent, :translated, :approved, :finished, :batch_assign, :batch_archive, :batch_upload, :batch_approve, :batch_archive_approved, :search, :search_generated, :search_assigned, :search_approved, :search_finished, :autocomplete_employee_name
      post :batch_assign, :batch_archive, :batch_upload, :batch_approve, :batch_archive_approved, :search_generated, :search_assigned, :search_approved, :search_finished
    end
    member do
      get :download
    end
    resources :comments
  end
  resources :users do
    resources :expertises
    collection do
      get 'edit_password'
      post 'update_password'
    end
  end
  resources :employees
  resources :mails
  match 'signin' => 'sessions#new', :as => :signin, :via => [:get]
  match 'signin' => 'sessions#create', :as => :signin, :via => [:post]
  match 'signout' => 'sessions#destroy', :as => :signout
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  ROLE_LINGUISTER, ROLE_EMBELLISHER, ROLE_READER, ROLE_EDITOR = 1, 2, 3, 4
end

app/controllers/employees_controller.rb
# -*- encoding : utf-8 -*-
class EmployeesController < ApplicationController
  
  def index
    @employees = Employee.paginate :page => params[:page]
  end
  
  def show
    @employee = Employee.find(params[:id])
  end
  
  def new
    @employee = Employee.new
  end
  
  def edit
    @employee = Employee.find(params[:id])
  end
  
  def create
    @employee = Employee.new(params[:employee])
    if @employee.save
      redirect_to(@employee, :notice => '创建成功')
    else
      render :action => "new"
    end
  end
  
  def update
    @employee = Employee.find(params[:id])
    if @employee.update_attributes(params[:employee])
      redirect_to(@employee, :notice => '更新成功')
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to(employees_url)
  end
end

app/views/employees/edit.html.erb
<h1>编辑雇员</h1>
<%= form_for @employee do |f| %>
  <%= render "shared/error_messages", :target => @employee %>
  <fieldset class="form-generic">
    <ul>
      <li><label>名称：</label><%= f.text_field :name, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>角色：</label><%= f.select :role, employee_role_options_for_select %></li>
    </ul>
    <ul>
      <li><label>公司名称：</label><%= f.text_field :company_name, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>职位：</label><%= f.text_field :title, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>电话号码：</label><%= f.text_field :phone_number, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>电子邮件：</label><%= f.text_field :email, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>联系地址：</label><%= f.text_field :address, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>邮政编码：</label><%= f.text_field :postal_code, :class => 'text-field' %></li>
    </ul>
    <div class="operation-generic">
      <%= link_to '修改', '#', :onclick => "submitForm('edit_employee_#{@employee.id}')", :class => 'button' %>
      <%= link_to '返回', @employee, :class => 'button' %>
      <%= link_to '雇员列表', employees_path, :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/employees/index.html.erb
<h1>雇员列表<span><%= link_to '添加雇员', new_employee_path %></span></h1>
<table class="list-generic">
  <tr>
    <th>ID</th>
    <th>名称</th>
    <th>角色</th>
    <th>操作</th>
  </tr>
  <% if @employees.blank? %>
    <%= raw empty_record_tag %>
  <% else %>
    <% @employees.each_with_index do |employee, index| %>
      <tr class="<%= odevity_tag index %>">
        <td><%= link_to employee.id, employee %></td>
        <td><%= employee.name %></td>
        <td><%= human_employee_role_for employee.role %></td>
        <td><%= raw crud_for_list_tag(employee) %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= will_paginate @employees %>

app/views/employees/new.html.erb
<h1>添加雇员</h1>
<%= form_for @employee do |f| %>
  <%= render "shared/error_messages", :target => @employee %>
  <fieldset class="form-generic">
    <ul>
      <li><label>名称：</label><%= f.text_field :name, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>角色：</label><%= f.select :role, employee_role_options_for_select %></li>
    </ul>
    <ul>
      <li><label>公司名称：</label><%= f.text_field :company_name, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>职位：</label><%= f.text_field :title, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>电话号码：</label><%= f.text_field :phone_number, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>电子邮件：</label><%= f.text_field :email, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>联系地址：</label><%= f.text_field :address, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>邮政编码：</label><%= f.text_field :postal_code, :class => 'text-field' %></li>
    </ul>
    <div class="operation-generic">
      <%= link_to '添加', '#', :onclick => "submitForm('new_employee')", :class => 'button' %>
      <%= link_to '雇员列表', employees_path, :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/employees/show.html.erb
<h1>查看雇员</h1>
<fieldset class="form-generic">
  <ul>
    <li><label>名称：</label><%= @employee.name %></li>
  </ul>
  <ul>
    <li><label>角色：</label><%= human_employee_role_for @employee.role %></li>
  </ul>
  <ul>
    <li><label>公司名称：</label><%= @employee.company_name %></li>
  </ul>
  <ul>
    <li><label>职位：</label><%= @employee.title %></li>
  </ul>
  <ul>
    <li><label>电话号码：</label><%= @employee.phone_number %></li>
  </ul>
  <ul>
    <li><label>电子邮件：</label><%= @employee.email %></li>
  </ul>
  <ul>
    <li><label>联系地址：</label><%= @employee.address %></li>
  </ul>
  <ul>
    <li><label>邮政编码：</label><%= @employee.postal_code %></li>
  </ul>
  <div class="operation-generic">
    <%= raw crud_for_show_tag(@employee) %>
  </div>
</fieldset>