config/routes.rb
# -*- encoding : utf-8 -*-
Trans::Application.routes.draw do
  root :to => 'home#index'
  resources :notices do
    collection do
      get :read, :unread
    end
  end
  resources :excels do
    collection do
      get :export_translations
      post :export_translations
    end
  end
  resources :categories
  resources :languages
  resources :documents do
    collection do
      get :uploaded, :batch_new, :batch_assign
      post :batch_create, :batch_assign
    end
    resources :comments
    resources :operations
    resources :translations
  end
  resources :translations do
    collection do
      get :generated, :assigned, :sent, :translated, :approved, :finished, :batch_assign, :batch_archive, :batch_upload, :batch_approve, :batch_archive_approved, :search, :search_generated, :search_assigned, :search_approved, :search_finished, :autocomplete_employee_name
      post :batch_assign, :batch_archive, :batch_upload, :batch_approve, :batch_archive_approved, :search_generated, :search_assigned, :search_approved, :search_finished
    end
    member do
      get :download
    end
    resources :comments
  end
  resources :users do
    resources :expertises
    collection do
      get 'edit_password'
      post 'update_password'
    end
  end
  resources :employees
  resources :mails
  match 'signin' => 'sessions#new', :as => :signin, :via => [:get]
  match 'signin' => 'sessions#create', :as => :signin, :via => [:post]
  match 'signout' => 'sessions#destroy', :as => :signout
end

app/models/category.rb
# -*- encoding : utf-8 -*-
class Category < ActiveRecord::Base
  acts_as_nested_set
  has_many :documents
  has_many :translations, :through => :documents, :source => :document
  before_create :setup_position
  
  def setup_position
    self.position = Category.where(self.parent_id.blank? ? 'parent_id IS NULL' : ['parent_id = ?', self.parent_id]).maximum('position').to_i + 1
  end
end

app/controllers/translations_controller.rb
# -*- encoding : utf-8 -*-
class TranslationsController < ApplicationController
  autocomplete :employee, :name
  
  def show
    @translation = Translation.find(params[:id])
    @comment = Comment.new
  end
  
  def edit
    @translation = Translation.find(params[:id])
  end
  
  def update
    @translation = Translation.find(params[:id])
    if @translation.update_attributes(params[:translation])
      redirect_to(@translation, :notice => '更新成功')
    else
      render :action => "edit"
    end
  end
  
  def download
    @translation = Translation.find(params[:id])
    send_file @translation.file.stored_path, :filename => @translation.human_file_name
  end
  
  def generated
    @translations = Translation.generated.paginate :page => params[:page]
  end
  
  def assigned
    if user_role_in_session == User::ROLE_ASSIGNEE
      @translations = Translation.assigned.assigned_for(user_id_in_session).paginate :page => params[:page]
    else
      @translations = Translation.assigned.paginate :page => params[:page]
    end
  end
  
  def sent
    if user_role_in_session == User::ROLE_ASSIGNEE
      @translations = Translation.sent.assigned_for(user_id_in_session).paginate :page => params[:page]
    else
      @translations = Translation.sent.paginate :page => params[:page]
    end
  end
  
  def translated
    if user_role_in_session == User::ROLE_ASSIGNEE
      @translations = Translation.translated.assigned_for(user_id_in_session).paginate :page => params[:page]
    else
      @translations = Translation.translated.paginate :page => params[:page]
    end
  end
  
  def approved
    if user_role_in_session == User::ROLE_ASSIGNEE
      @translations = Translation.approved.assigned_for(user_id_in_session).paginate :page => params[:page]
    else
      @translations = Translation.approved.paginate :page => params[:page]
    end
  end
  
  def finished
    if user_role_in_session == User::ROLE_EDITOR
      @translations = Translation.finished.paginate :page => params[:page]
    elsif user_role_in_session == User::ROLE_ASSIGNEE
      @translations = Translation.finished.assigned_for(user_id_in_session).paginate :page => params[:page]
    else
      @translations = Translation.finished.paginate :page => params[:page]
    end
  end
  
  def batch_assign
    @translations = Translation.generated
    if request.post?
      path = params[:searched] ? search_generated_translations_path : batch_assign_translations_path
      if params[:translation_ids].blank?
        redirect_to path, :alert => '操作失败，请至少选择一个外文文档！'
      elsif params[:assignee_id].blank?
        redirect_to path, :alert => '操作失败，请选择指派人！'
      else
        Translation.batch_assign user_id_in_session, params[:translation_ids], params[:assignee_id]
        redirect_to path, :notice => '批量指派成功'
      end
    end
  end
  
  def batch_archive
    if user_role_in_session == User::ROLE_ASSIGNEE
      @translations = Translation.assigned.assigned_for user_id_in_session
    else
      @translations = Translation.assigned
    end
    if request.post?
      if params[:translation_ids].blank?
        redirect_to (params[:searched] ? search_assigned_translations_path : batch_archive_translations_path), :alert => '操作失败，请至少选择一个外文文档！'
      else
        archive_name = Translation.batch_archive user_id_in_session, params[:translation_ids]
        send_file "#{::Rails.root.to_s}/public/archives/#{archive_name}", :filename => archive_name, :type => 'application/octet-stream'
      end
    end
  end
  
  def batch_upload
    if request.post?
      if params[:file].blank?
        redirect_to batch_upload_translations_path, :alert => '请正确选择文件'
      elsif params[:file].content_type != 'application/octet-stream'
        redirect_to batch_upload_translations_path, :alert => '请选择RAR文件，其它格式的文件无法提交'
      else
        @unknown_files = Translation.batch_upload user_id_in_session, params[:file].read
        if @unknown_files.blank?
          redirect_to batch_upload_translations_path, :notice => '批量上传翻译文档成功'
        else
          render 'batch_upload_result'
        end
      end
    end
  end
  
  def batch_approve
    @translations = Translation.translated
    if request.post?
      if params[:translation_ids].blank?
        redirect_to batch_approve_translations_path, :alert => '操作失败，请至少选择一个外文文档！'
      else
        Translation.batch_approve user_id_in_session, params[:translation_ids]
        redirect_to batch_approve_translations_path, :notice => '批量审核成功'
      end
    end
  end
  
  def batch_archive_approved
    @translations = Translation.approved
    if request.post?
      if params[:translation_ids].blank?
        redirect_to (params[:searched] ? search_approved_translations_path : batch_archive_translations_path), :alert => '操作失败，请至少选择一个外文文档！'
      else
        archive_name = Translation.batch_archive user_id_in_session, params[:translation_ids]
        send_file "#{::Rails.root.to_s}/public/archives/#{archive_name}", :filename => archive_name, :type => 'application/octet-stream'
      end
    end
  end
  
  def batch_archive_finished
    @translations = Translation.approved
    if request.post?
      if params[:translation_ids].blank?
        redirect_to (params[:searched] ? search_approved_translations_path : batch_archive_translations_path), :alert => '操作失败，请至少选择一个外文文档！'
      else
        archive_name = Translation.batch_archive user_id_in_session, params[:translation_ids]
        send_file "#{::Rails.root.to_s}/public/archives/#{archive_name}", :filename => archive_name, :type => 'application/octet-stream'
      end
    end
  end
  
  def search
    unless params[:keywords].blank?
      @translations = Translation.search(params[:keywords]).paginate :page => params[:page]
      render 'search_result'
    end
  end
  
  def search_generated
    if request.get?
      render 'translations/search/generated'
    else
      @translations = Translation.advanced_search Translation::STATE_GENERATED, params
      render 'translations/search/generated_result'
    end
  end
  
  def search_assigned
    if request.get?
      render 'translations/search/assigned'
    else
      @translations = Translation.advanced_search Translation::STATE_ASSIGNED, params
      render 'translations/search/assigned_result'
    end
  end
  
  def search_approved
    if request.get?
      render 'translations/search/approved'
    else
      @translations = Translation.advanced_search Translation::STATE_APPROVED, params
      render 'translations/search/approved_result'
    end
  end
  
  def search_finished
    if request.get?
      render 'translations/search/finished'
    else
      @translations = Translation.advanced_search Translation::STATE_FINISHED, params
      render 'translations/search/finished_result'
    end
  end
end

app/views/translations/approved.html.erb
<h1>已审核外文文档列表</h1>
<table class="list-generic">
  <tr>
    <th>ID</th>
    <th>所属分类</th>
    <th>中文文档标题</th>
    <th>翻译语种</th>
    <th>审核时间</th>
  </tr>
  <% if @translations.blank? %>
    <%= raw empty_record_tag %>
  <% else %>
    <% @translations.each_with_index do |translation, index| %>
      <tr class="<%= odevity_tag index %>">
        <td><%= link_to translation.id, translation %></td>
        <td><%= translation.document.category.name %></td>
        <td><%= translation.document.title %></td>
        <td><%= translation.language.name %></td>
        <td><%= human_datetime_for translation.approved_at %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= will_paginate @translations %>

app/views/translations/assigned.html.erb
<h1>待翻译外文文档列表<span><%= link_to '高级搜索', search_assigned_translations_path %></span></h1>
<table class="list-generic">
  <tr>
    <th>ID</th>
    <th>中文文档标题</th>
    <th>翻译语种</th>
    <th>指派人</th>
    <th>指派时间</th>
  </tr>
  <% if @translations.blank? %>
    <%= raw empty_record_tag %>
  <% else %>
    <% @translations.each_with_index do |translation, index| %>
      <tr class="<%= odevity_tag index %>">
        <td><%= link_to translation.id, translation %></td>
        <td><%= translation.document.title %></td>
        <td><%= translation.language.name %></td>
        <td><%= translation.assignee.name %></td>
        <td><%= human_datetime_for translation.assigned_at %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= will_paginate @translations %>

app/views/translations/batch_approve.html.erb
<h1>批量审核外文文档</h1>
<%= form_tag batch_approve_translations_path, :id => 'batch_approve' do %>
<table class="list-generic">
  <tr>
    <th>&nbsp;</th>
    <th>分类</th>
    <th>中文标题</th>
    <th>翻译语言</th>
  </tr>
  <% if @translations.blank? %>
    <%= raw empty_record_tag %>
  <% else %>
    <% @translations.each_with_index do |translation, index| %>
      <tr class="<%= odevity_tag index %>">
        <td><%= check_box_tag 'translation_ids[]', translation.id %></td>
        <td><%= translation.document.category.name %></td>
        <td><%= translation.document.title %></td>
        <td><%= translation.language.name %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= link_to "全选（共#{@translations.count}篇）", "javascript:;", :onclick => "javascript:selectOrDeselectCheckbox(true, 'translation_ids[]'); return false;" %> / <%= link_to '全不选', "javascript:;", :onclick => "javascript:selectOrDeselectCheckbox(false, 'translation_ids[]'); return false;" %>
<div class="separator"></div>
<%= link_to '批量审核', '#', :onclick => "submitForm('batch_approve')", :class => 'button' %>
<% end %>

app/views/translations/batch_archive.html.erb
<h1>批量归档待翻译外文文档</h1>
<%= form_tag batch_archive_translations_path, :id => 'batch_archive' do %>
<table class="list-generic">
  <tr>
    <th>&nbsp;</th>
    <th>中文文档标题</th>
    <th>翻译语言</th>
    <th>指派人</th>
  </tr>
  <% if @translations.blank? %>
    <%= raw empty_record_tag %>
  <% else %>
    <% @translations.each_with_index do |translation, index| %>
      <tr class="<%= odevity_tag index %>">
        <td><%= check_box_tag 'translation_ids[]', translation.id %></td>
        <td><%= translation.document.title %></td>
        <td><%= translation.language.name %></td>
        <td><%= translation.assignee.name %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= link_to "全选（共#{@translations.count}篇）", "javascript:;", :onclick => "javascript:selectOrDeselectCheckbox(true, 'translation_ids[]'); return false;" %> / <%= link_to '全不选', "javascript:;", :onclick => "javascript:selectOrDeselectCheckbox(false, 'translation_ids[]'); return false;" %>
<div class="separator"></div>
<%= link_to '批量归档', '#', :onclick => "submitForm('batch_archive')", :class => 'button' %>
<% end %>

app/views/translations/batch_archive_approved.html.erb
<h1>批量归档已审核外文文档</h1>
<%= form_tag batch_archive_approved_translations_path, :id => 'batch_archive_approved' do %>
<table class="list-generic">
  <tr>
    <th>&nbsp;</th>
    <th>中文文档标题</th>
    <th>翻译语言</th>
    <th>指派人</th>
  </tr>
  <% if @translations.blank? %>
    <%= raw empty_record_tag %>
  <% else %>
    <% @translations.each_with_index do |translation, index| %>
      <tr class="<%= odevity_tag index %>">
        <td><%= check_box_tag 'translation_ids[]', translation.id %></td>
        <td><%= translation.document.title %></td>
        <td><%= translation.language.name %></td>
        <td><%= translation.assignee.name %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= link_to "全选（共#{@translations.count}篇）", "javascript:;", :onclick => "javascript:selectOrDeselectCheckbox(true, 'translation_ids[]'); return false;" %> / <%= link_to '全不选', "javascript:;", :onclick => "javascript:selectOrDeselectCheckbox(false, 'translation_ids[]'); return false;" %>
<div class="separator"></div>
<%= link_to '批量归档', '#', :onclick => "submitForm('batch_archive_approved')", :class => 'button' %>
<% end %>

app/views/translations/batch_upload_result.html.erb
<h1>批量上传翻译外文文档结果</h1>
<p>以下<%= @unknown_files.size %>个文件未能成功上传：</p>
<ul>
  <% @unknown_files.each do |unknown_file| %>
    <li><%= unknown_file %></li>
  <% end %>
</ul>
<div class="operation-generic">
  <%= link_to '返回', batch_upload_translations_path, :class => 'button' %>
</div>

app/views/translations/edit.html.erb
<h1>编辑文档</h1>
<%= form_for @translation do |f| %>
  <%= render "shared/error_messages", :target => @translation %>
  <fieldset class="form-generic">
    <ul>
      <li><label>所属分类：</label><%= @translation.document.category.ancestors.map{|n| n.name}.join '-' %></li>
    </ul>
    <ul>
      <li><label>中文文档标题：</label><%= @translation.document.title %></li>
    </ul>
    <ul>
      <li><label>翻译语言：</label><%= @translation.language.name %></li>
    </ul>
    <ul>
      <li><label>状态：</label><%= human_translation_state_for @translation.state %></li>
    </ul>
    <ul>
      <li>
        <label>译员：</label>
        <%= f.autocomplete_field :linguister_id, autocomplete_employee_name_translations_path, :class => 'text-field' %>
        <%= link_to '添加译员', new_employee_path, :class => 'button' %>
      </li>
    </ul>
    <ul>
      <li>
        <label>润色：</label>
        <%= f.text_field :embellisher, :class => 'text-field' %>
        <%= link_to '添加润色', new_employee_path, :class => 'button' %>
      </li>
    </ul>
    <ul>
      <li>
        <label>审稿：</label>
        <%= f.text_field :reader, :class => 'text-field' %>
        <%= link_to '添加审稿', new_employee_path, :class => 'button' %>
      </li>
    </ul>
    <ul>
      <li>
        <label>编辑：</label>
        <%= f.text_field :editor, :class => 'text-field' %>
        <%= link_to '添加编辑', new_employee_path, :class => 'button' %>
      </li>
    </ul>
    <div class="operation-generic">
      <%= link_to '修改', '#', :onclick => "submitForm('edit_translation_#{@translation.id}')", :class => 'button' %>
      <%= link_to '返回', @translation, :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/translations/finished.html.erb
<h1>已定稿外文文档列表</h1>
<table class="list-generic">
  <tr>
    <th>ID</th>
    <th>所属分类</th>
    <th>中文文档标题</th>
    <th>翻译语种</th>
    <th>指派人</th>
    <th>定稿时间</th>
  </tr>
  <% if @translations.blank? %>
    <%= raw empty_record_tag %>
  <% else %>
    <% @translations.each_with_index do |translation, index| %>
      <tr class="<%= odevity_tag index %>">
        <td><%= link_to translation.id, translation %></td>
        <td><%= translation.document.category.name %></td>
        <td><%= translation.document.title %></td>
        <td><%= translation.language.name %></td>
        <td><%= translation.assignee.name %></td>
        <td><%= human_datetime_for translation.finished_at %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= will_paginate @translations %>

app/views/translations/search_approved.html.erb
<h1>搜索已审核外文文档</h1>
<%= form_tag search_approved_translations_path, :id => 'search_approved_translations' do %>
  <fieldset class="form-generic">
    <ul>
      <li><label>所属分类：</label><%= select_tag :category_id, options_for_select(nested_set_options(Category) {|i| "#{'-' * i.level} #{i.name}" } ), :prompt => '不限' %></li>
    </ul>
    <ul>
      <li><label>关键词：</label><%= text_field_tag :keywords, nil, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li>
        <label>翻译语种：</label>
        <div class="languages">
          <%= raw all_languages.map {|l| "<span>#{check_box_tag 'language_ids[]', l.id} #{l.name}</span>"}.join ' ' %>
          <div class="action"><%= link_to '全选', "javascript:;", :onclick => "javascript:selectOrDeselectCheckbox(true, 'language_ids[]'); return false;" %> / <%= link_to '全不选', "javascript:;", :onclick => "javascript:selectOrDeselectCheckbox(false, 'language_ids[]'); return false;" %> / <%= link_to '选择8种大语言', "javascript:;", :onclick => "javascript:selectPopularLanguages('language_ids[]'); return false;" %> / <%= link_to '选择36种小语言', "javascript:;", :onclick => "javascript:selectUnpopularLanguages('language_ids[]'); return false;" %></div>
        </div>
        </li>
    </ul>
    <ul>
      <li><label>译稿提交日期：</label><%= date_select :date_range, :begin, :use_month_numbers => true, :start_year => 2011, :prompt => { :year => '年', :month => '月', :day => '日' } %> 至 <%= date_select :date_range, :end, :use_month_numbers => true, :start_year => 2011, :prompt => { :year => '年', :month => '月', :day => '日' } %></li>
    </ul>
    <div class="operation-generic">
      <%= link_to '搜索', '#', :onclick => "submitForm('search_approved_translations')", :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/translations/search_approved_result.html.erb
<h1>搜索已审核外文文档结果<span><%= link_to '重新搜索', search_approved_translations_path %></span></h1>
<%= form_tag batch_archive_translations_path, :id => 'batch_archive' do %>
<table class="list-generic">
  <tr>
    <th>&nbsp;</th>
    <th>所属分类</th>
    <th>中文文档标题</th>
    <th>翻译语言</th>
    <th>最终回稿时间</th>
  </tr>
  <% if @translations.blank? %>
    <%= raw empty_record_tag %>
  <% else %>
    <% @translations.each_with_index do |translation, index| %>
      <tr class="<%= odevity_tag index %>">
        <td><%= check_box_tag 'translation_ids[]', translation.id %></td>
        <td><%= translation.document.category.name %></td>
        <td><%= translation.document.title %></td>
        <td><%= translation.language.name %></td>
        <td><%= human_datetime_for translation.translated_at %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= link_to '全选', "javascript:;", :onclick => "javascript:selectOrDeselectCheckbox(true, 'translation_ids[]'); return false;" %> / <%= link_to '全不选', "javascript:;", :onclick => "javascript:selectOrDeselectCheckbox(false, 'translation_ids[]'); return false;" %>
<div class="separator"></div>
<%= link_to '批量归档', '#', :onclick => "submitForm('batch_archive')", :class => 'button' %>
<% end %>

app/views/translations/search_result.html.erb
<h1>“<%= params[:keywords] %>”的搜索结果<span><%= link_to '重新搜索', search_translations_path %></span></h1>
<table class="list-generic">
  <tr>
    <th>ID</th>
    <th>所属分类</th>
    <th>中文文档标题</th>
    <th>翻译语种</th>
    <th>指派人</th>
    <th>状态</th>
  </tr>
  <% if @translations.blank? %>
    <%= raw empty_record_tag %>
  <% else %>
    <% @translations.each_with_index do |translation, index| %>
      <tr class="<%= odevity_tag index %>">
        <td><%= link_to translation.id, translation %></td>
        <td><%= translation.document.category.name %></td>
        <td><%= translation.document.title %></td>
        <td><%= translation.language.name %></td>
        <td><%= translation.assignee.name %></td>
        <td><%= human_translation_state_for translation.state %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= will_paginate @translations %>

app/views/translations/sent.html.erb
<h1>已送翻外文文档列表</h1>
<table class="list-generic">
  <tr>
    <th>ID</th>
    <th>所属分类</th>
    <th>中文文档标题</th>
    <th>翻译语种</th>
    <th>指派人</th>
    <th>送翻时间</th>
  </tr>
  <% if @translations.blank? %>
    <%= raw empty_record_tag %>
  <% else %>
    <% @translations.each_with_index do |translation, index| %>
      <tr class="<%= odevity_tag index %>">
        <td><%= link_to translation.id, translation %></td>
        <td><%= translation.document.category.name %></td>
        <td><%= translation.document.title %></td>
        <td><%= translation.language.name %></td>
        <td><%= translation.assignee.name %></td>
        <td><%= human_datetime_for translation.sent_at %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= will_paginate @translations %>

app/views/translations/show.html.erb
<h1>查看文档<span><%= raw([permissable_for([User::ROLE_HF_MANAGER]){"#{link_to '编辑', edit_translation_path(@translation)}"}, permissable_for([User::ROLE_CIO_MANAGER]){"#{link_to '编辑中文文档', edit_document_path(@translation.document)}"}].join ' | ') %></span></h1>
<fieldset class="form-generic">
  <ul>
    <li><label>所属分类：</label><%= @translation.document.category.ancestors.map{|n| n.name}.join '-' %></li>
  </ul>
  <ul>
    <li><label>中文文档标题：</label><%= @translation.document.title %></li>
  </ul>
  <ul>
    <li><label>翻译语言：</label><%= @translation.language.name %></li>
  </ul>
  <ul>
    <li><label>字数统计：</label><%= @translation.document.word_count %></li>
  </ul>
  <ul>
    <li><label>状态：</label><%= human_translation_state_for @translation.state %></li>
  </ul>
  <ul>
    <li><label>原始中文文档：</label><%= link_to '点击下载', @translation.document.file.uri %></li>
  </ul>
  <ul>
    <li><label>翻译文档：</label><%= link_to '点击下载', download_translation_path(@translation) unless @translation.file.blank? %></li>
  </ul>
  <ul>
    <li><label>译员：</label><%= @translation.linguister.name unless @translation.linguister.blank? %></li>
  </ul>
  <ul>
    <li><label>润色：</label><%= @translation.embellisher.name unless @translation.embellisher.blank? %></li>
  </ul>
  <ul>
    <li><label>审稿：</label><%= @translation.reader.name unless @translation.reader.blank? %></li>
  </ul>
  <ul>
    <li><label>编辑：</label><%= @translation.editor.name unless @translation.editor.blank? %></li>
  </ul>
</fieldset>
<div class="separator"></div>
<ul class="operations">
  <% @translation.operations.ordered.each do |operation| %>
    <li><%= operation.user.name %> 于 <%= human_datetime_for operation.created_at %> 进行了 <%= human_operation_action_for operation.action %> 操作</li>
  <% end %>
</ul>
<div class="separator"></div>
<ul class="comments">
  <% @translation.comments.each do |comment| %>
    <li><%= comment.user.name %> 在 <%= human_datetime_for comment.created_at %> 说：<%= comment.content %></li>
  <% end %>
</ul>
<div class="separator"></div>
<%= form_for [@translation, @comment] do |f| %>
  <div class="new-comment">
    <%= f.text_area :content %>
    <%= link_to '发表评论', '#', :onclick => "submitForm('new_comment')", :class => 'button' %>
  </div>
<% end %>

app/views/translations/translated.html.erb
<h1>待审核文档列表</h1>
<table class="list-generic">
  <tr>
    <th>ID</th>
    <th>所属分类</th>
    <th>中文文档标题</th>
    <th>翻译语种</th>
    <th>指派人</th>
    <th>最终回稿时间</th>
  </tr>
  <% if @translations.blank? %>
    <%= raw empty_record_tag %>
  <% else %>
    <% @translations.each_with_index do |translation, index| %>
      <tr class="<%= odevity_tag index %>">
        <td><%= link_to translation.id, translation %></td>
        <td><%= translation.document.category.name %></td>
        <td><%= translation.document.title %></td>
        <td><%= translation.language.name %></td>
        <td><%= translation.assignee.name %></td>
        <td><%= human_datetime_for translation.translated_at %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= will_paginate @translations %>