config/routes.rb
# -*- encoding : utf-8 -*-
Trans::Application.routes.draw do
  root :to => 'home#index'
  resources :notices do
    collection do
      get :read, :unread
    end
  end
  resources :excels do
    collection do
      get :export_translations
      post :export_translations
    end
  end
  resources :categories
  resources :languages
  resources :documents do
    collection do
      get :uploaded, :batch_new, :batch_assign
      post :batch_create, :batch_assign
    end
    resources :comments
    resources :operations
    resources :translations
  end
  resources :translations do
    collection do
      get :generated, :assigned, :sent, :translated, :approved, :finished, :batch_assign, :batch_archive, :batch_upload, :batch_approve, :batch_archive_approved, :search, :search_generated, :search_assigned, :search_approved, :search_finished, :autocomplete_employee_name
      post :batch_assign, :batch_archive, :batch_upload, :batch_approve, :batch_archive_approved, :search_generated, :search_assigned, :search_approved, :search_finished
    end
    member do
      get :download
    end
    resources :comments
  end
  resources :users do
    resources :expertises
    collection do
      get 'edit_password'
      post 'update_password'
    end
  end
  resources :employees
  resources :mails
  match 'signin' => 'sessions#new', :as => :signin, :via => [:get]
  match 'signin' => 'sessions#create', :as => :signin, :via => [:post]
  match 'signout' => 'sessions#destroy', :as => :signout
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  ROLE_ADMIN, ROLE_CIO_MANAGER, ROLE_EDITOR, ROLE_HF_MANAGER, ROLE_ASSIGNEE = 1, 2, 3, 4, 5  
  attr_accessor :password
  before_create :generate_hashed_password
  validates_presence_of :account, :password, :password_confirmation, :on => :create
  validates_length_of :account, :password, :password_confirmation,:in => 4..16, :on => :create
  validates_uniqueness_of :account, :on => :create
  validates_confirmation_of :password, :on => :create
  scope :editors, where(role:ROLE_EDITOR)
  scope :assignee, where(role:ROLE_ASSIGNEE)
  
  def generate_hashed_password
    self.hashed_password = Digest::MD5.hexdigest self.password
  end
  
  class << self
    def signin account, password
      self.find_by_account_and_hashed_password account, Digest::MD5.hexdigest(password)
    end
  end
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  
  def index
    case user_role_in_session
    when User::ROLE_ADMIN
      @users = User.paginate :page => params[:page]
    when User::ROLE_CIO_MANAGER
      @users = User.editors.paginate :page => params[:page]
    when User::ROLE_HF_MANAGER
      @users = User.assignees.paginate :page => params[:page]
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to(@user, :notice => '创建成功')
    else
      render :action => "new"
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to(@user, :notice => '更新成功')
    else
      render :action => "edit"
    end
  end
  
  def update_password
    user = User.find user_id_in_session
    if user.hashed_password != Digest::MD5.hexdigest(params[:original_password])
      flash[:alert] = '原密码输入不正确，请重试'
    elsif params[:new_password] != params[:confirmed_password]
      flash[:alert] = '两次新密码输入不一致，请重试'
    elsif params[:new_password].blank?
      flash[:alert] = '新密码不能为空，请重试'
    elsif params[:new_password] !~ /^[a-zA-Z0-9_]{6,16}$/
      flash[:alert] = '新密码只能由大小写英文字母、数字和下划线组成，请重试'
    else
      user.update_attribute :hashed_password, Digest::MD5.hexdigest(params[:new_password])
      flash[:notice] = '密码修改成功'
    end
    redirect_to edit_password_users_path
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(users_url)
  end
end

app/views/users/edit.html.erb
<h1>编辑用户</h1>
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", :target => @user %>
  <fieldset class="form-generic">
    <ul>
      <li><label>账号：</label><%= @user.account %></li>
    </ul>
    <ul>
      <li><label>姓名：</label><%= f.text_field :name, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>角色：</label><%= f.select :role, user_role_options_for_select(:selected => @user.role) %></li>
    </ul>
    <ul>
      <li><label>禁用该账号：</label><%= f.check_box :prohibited %></li>
    </ul>
    <div class="operation-generic">
      <%= link_to '修改', '#', :onclick => "submitForm('edit_user_#{@user.id}')", :class => 'button' %>
      <%= link_to '用户列表', users_path, :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/users/edit_password.html.erb
<h1>修改密码</h1>
<%= form_tag update_password_users_path, :id => :edit_password do %>
  <fieldset class="form-generic">
    <ul>
      <li><label>原密码：</label><%= password_field_tag :original_password, nil, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>新密码：</label><%= password_field_tag :new_password, nil, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>确认新密码：</label><%= password_field_tag :confirmed_password, nil, :class => 'text-field' %></li>
    </ul>
    <div class="operation-generic">
      <%= link_to '修改', '#', :onclick => "submitForm('edit_password')", :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/users/index.html.erb
<h1>用户列表<span><%= link_to '添加用户', new_user_path %></span></h1>
<table class="list-generic">
  <tr>
    <th>ID</th>
    <th>账号</th>
    <th>姓名</th>
    <th>角色</th>
    <th>是否可用</th>
    <th>操作</th>
  </tr>
  <% if @users.blank? %>
    <%= raw empty_record_tag %>
  <% else %>
    <% @users.each_with_index do |user, index| %>
      <tr class="<%= odevity_tag index %>">
        <td><%= link_to user.id, user %></td>
        <td><%= user.account %></td>
        <td><%= user.name %></td>
        <td><%= human_user_role_for user.role %></td>
        <td><%= human_boolean_for !user.prohibited %></td>
        <td><%= raw crud_for_list_tag(user, :discard_destroy => true) %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= will_paginate @users %>

app/views/users/new.html.erb
<h1>添加用户</h1>
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", :target => @user %>
  <fieldset class="form-generic">
    <ul>
      <li><label>账号：</label><%= f.text_field :account, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>密码：</label><%= f.password_field :password, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>确认密码：</label><%= f.password_field :password_confirmation, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>姓名：</label><%= f.text_field :name, :class => 'text-field' %></li>
    </ul>
    <ul>
      <li><label>角色：</label><%= f.select :role, user_role_options_for_select %></li>
    </ul>
    <ul>
      <li><label>禁用该账号：</label><%= f.check_box :prohibited %></li>
    </ul>
    <div class="operation-generic">
      <%= link_to '添加', '#', :onclick => "submitForm('new_user')", :class => 'button' %>
      <%= link_to '用户列表', users_path, :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/users/show.html.erb
<h1>查看雇员</h1>
<fieldset class="form-generic">
  <ul>
    <li><label>账号：</label><%= @user.account %></li>
  </ul>
  <ul>
    <li><label>姓名：</label><%= @user.name %></li>
  </ul>
  <ul>
    <li><label>角色：</label><%= human_user_role_for @user.role %></li>
  </ul>
  <ul>
    <li><label>是否可用：</label><%= human_boolean_for !@user.prohibited? %></li>
  </ul>
  <ul>
    <li><label>最后登录时间：</label><%= human_datetime_for @user.last_signined_at %></li>
  </ul>
  <div class="operation-generic">
    <%= raw crud_for_show_tag(@user, :discard_destroy => true) %>
  </div>
</fieldset>